[project]
name = "aws-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.41.0",
    "python-dotenv>=1.2.1",
    "strands-agents[gemini]>=1.17.0",
]
